baseURL: "https://thebestsellerpolymon.github.io/practice-2025-1/"
title: Practice 2025
copyright: "© ODC project"
theme: [hugo-PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["blog"]

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 5

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Главная
          url: /
          weight: 1
        - name: О проекте
          url: /about/
          weight: 2
        - name: Участники
          url: /team/
          weight: 3
        - name: Журнал
          url: /blog/
          weight: 4
        - name: Ресурсы
          url: /resources/
          weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Сайт проекта ODC — цифровые наличные и открытый протокол передачи"
  author: ODC Team
  defaultTheme: auto
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  images: ["images/papermod-cover.png"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
